name: initsurvey
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.0.4
  connectivity: ^0.4.8+2
  shared_preferences: ^0.5.6+3
  http: ^0.12.0+4
  webview_flutter: ^0.3.19+9

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/ui/
    - assets/images/locale/
    - assets/images/pattern/
    # Data
    - assets/datas/
    - assets/administrations/
    - assets/administrations/quan-huyen/
    - assets/administrations/xa-phuong/
    # Locale
    - assets/locale/en/
    - assets/locale/vi/
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
